### ISSUE TITLE
error: duplicate value for resource 'attr/fontStyle' with config ''.

### ISSUE THREAD

**Issue by nagarajks88** [TakuSemba/Spotlight#75] opened 2019-07-12 11:13 UTC
Once I imported 'SpotLight' library, i am getting above issue .. Kindly help..

org.gradle.execution.MultipleBuildFailures: Build completed with 1 failures.
AAPT: error: duplicate value for resource 'attr/fontStyle' with config ''.
AAPT: error: resource previously defined here.

**Comment by TakuSemba** [comment] 2019-09-05 23:32
I can take a look if you could give me a sample code that I can reproduce.

**Comment by TakuSemba** [comment] 2019-11-10 19:29
I'm closing this due to the lack of information.

**Closed by TakuSemba** 2019-11-10 19:29 UTC
