### ISSUE TITLE
OnSpotlightEndedListener isn't called if an OnStarted listener isn't also set

### ISSUE THREAD

**Issue by UsernameInvalidException** [TakuSemba/Spotlight#4] opened 2017-07-10 18:06 UTC
Any code inside an OnSpotlightEndedListener isn't called unless an OnSpotlightStartedListener is also set.

**Comment by n1lsB** [comment] 2017-07-10 19:10
I think at line [246](https://github.com/TakuSemba/Spotlight/blob/master/spotlight/src/main/java/com/takusemba/spotlight/Spotlight.java#L246) of Spotlight.java instead of

`if (startedListener != null) endedListener.onEnded();`

it should be

`if (endedListener != null) endedListener.onEnded();`

**Comment by UsernameInvalidException** [comment] 2017-07-10 21:11
I think you're right. Let me try that in my fork and see if it fixes the issue

**Comment by TakuSemba** [comment] 2017-07-11 01:45
yea, thats the cause. thanks for telling me.

**Comment by TakuSemba** [comment] 2017-07-11 15:52
I have just fixed this. I will release 1.0.2 soon.

**Comment by TakuSemba** [comment] 2017-07-12 15:22
1.0.2 released, im closing this

**Closed by TakuSemba** 2017-07-12 15:22 UTC
